name: "hello world workflow / pipeline"
on:
 push:
 # schedule:
 #   - cron: '3,33 * * * *'
 workflow_dispatch:

jobs:
  hello_world_job:
   runs-on: ubuntu-latest
   steps:
     - name: "print event type"
       run: echo "event type is - ${{github.event_name}}"
     - name: "greet to world step" 
       run: echo "Hello World"
     - name: "print current time"
       run: echo "current time is $(date)"
 
